# Generated by Django 3.0.5 on 2020-06-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200623_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='og_description',
            field=models.CharField(max_length=2000),
        ),
    ]
