# Generated by Django 3.0.5 on 2020-06-25 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200624_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='topics',
            new_name='topic',
        ),
    ]
