# Generated by Django 3.0.5 on 2020-06-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200625_0317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='resource',
            name='date',
            field=models.DateField(default='2020-06-24', verbose_name='resource date'),
            preserve_default=False,
        ),
    ]
